### ISSUE TITLE
 .gdme filetype for distributable guide files.

### ISSUE THREAD

**Issue by meson1** [guide-me/GuideMe#13]
Create a .gdme filetype. Basically it would be a zip file containing the xml file and the media directory. It would have light encryption applied with a simple password of "guideme" to facilitate sharing of said files without detection of any pornographic content by hosting sites.
This could be implemented by including 7zip DLL, which I understand is allowed under 7zip's license (but you'd have to double check that).
Your GuideMe/TeaseMe authoring tool could export gdme files.  And GuideMe could import them.  At the same time, the gdme files would be simple enough to create or extract from by hand.

**Comment by philormand** [comment]
Implemented as tools compress / uncompress guide on the menu
