### ISSUE TITLE
Allow Timer node to be created and started from Javascript.

### ISSUE THREAD

**Issue by meson1** [guide-me/GuideMe#36]
Exactly what it says on the tin.

A javascript equivalent of the XML <Timer /> element, so Timer nodes can be created dynamically.

Also JS created Timer nodes should take effect from when they are created rather than from when the page is loaded (either that or include a means of starting the timers).  That way the programmer create a new Timer node as part of the script run by the previous one, so as to facilitate a succession of events without having to reload the page.

Example, running the script on page load I create a Timer node for 25 seconds time.  After 25 seconds when the subsequent function runs, I want to create a new Timer node for 15 seconds time and then that one creates another new Timer node for another 60 seconds time.  All without having to reload the page.

**Comment by philormand** [comment]
Added a function (addTimer) to both overRide and guide
(overRide will trigger from the point the page loads, guide from the point the timer is added)
delay                time in seconds before the timer triggers
jScript               javascript function to run when the timer triggers
imageId            image to change to when the timer triggers
text                   html text to set the right html pane when the timer triggers
set                    flags to set when the timer triggers
unSet               flags to clear when the timer triggers
