### ISSUE TITLE
Compile Instructions

### ISSUE THREAD

**Issue by dede1234dede** [guide-me/GuideMe#38]
Hello, 

Could you provide some instructions on how to compile / what the dependencies are? 
I'd like to make a Linux build, and I think we may be able to make a cross platform build.

Thanks

**Comment by philormand** [comment]
The project uses maven so the dependencies are defined in the pom.xml.
The main gotchas to look out for are whether you are using 32bit or 64bit.
Java, SWT and VLC have to either all be 32bit or all be 64bit.
The only other issue should be anywhere where paths have been hard coded as a \

Currently I just over write org.eclipse.swt.win32.win32.x86_64-4.3.jar with the correct version of the swt jar for the operating system / 32/64bit.

There are some helper functions in comonFuctions 
getOs(), onMac(), onWindows(), onUnix(), fixSeparator()
and appSettings getFileSeparator()
That can be used to fix any hard coded paths

I have had a version of guideme working on linux, but it was a while ago.
