### ISSUE TITLE
Show a list of new (available) guides on the welcome page.

### ISSUE THREAD

**Issue by TakenagaT** [guide-me/GuideMe#4]
There should be a configuration property pointing to an RSS feed with new guides.

**Comment by meson1** [comment]
In the XML, in addition to <Title> and <Author> elements, have a <Synopsis> element.  The <Synopsis> can then be used to contain a brief description of the Guide and can be displayed on the welcome page.
Also in the Media Directory, if there is a file called cover.jpg, that can be used as the basis for a thumbnail on the welcome screen.

**Comment by philormand** [comment]
There is now a library menu option that will display a list of teases
